### ISSUE TITLE
1.13.1 fill - trees cut off on chunk borders

### ISSUE THREAD

**Issue by eightbitx** [Brettflan/WorldBorder#105]
Screenshot: https://i.imgur.com/5WdSbJD.png

Running Paper-225 for MC 1.13.1. Using version of WorldBorder compiled from Github source on 8/31/18.

**Comment by Brettflan** [comment]
Previously reported and closed by the reporter; seems like it's a 1.13 bug not specific to WorldBorder's Fill.
https://github.com/Brettflan/WorldBorder/issues/98

**Comment by eightbitx** [comment]
I can't seem to replicate it in a single-player vanilla world. I also can't find any broken trees in a world that I filled using regular Spigot. Might be a Paper-Spigot issue?

**Comment by TheCompieter** [comment]
@eightbitx 
https://bugs.mojang.com/browse/MC-125007 This is the bug.

**Comment by eightbitx** [comment]
@TheCompieter Thanks, I saw it. During my testing I was unable to find any broken trees in vanilla nor in a world that I /fill(ed) with regular Spigot. I'm guessing this is a vanilla bug, but whatever code PaperSpigot changed made it much worse.
