### ISSUE TITLE
1.9.0 build from Spigot - crashed server on /wb bypass <username>

### ISSUE THREAD

**Issue by smmmadden** [Brettflan/WorldBorder#108]
I've installed the latest version of WorldBorder for 1.13.1 and I'm using PaperSpigot build 262 (1.13.1) with Dynmap-3.0-SNAPSHOT-spigot.jar (1.13.1).  I issued a wb bypass smmmadden from the console and it worked perfectly and updated the config file automatically.  I then went into the game and issued the same command for my wife's admin account and the config was updated, but server crashed immediately afterward.

See crash report here
[crash-2018-09-16_23.04.02-server.txt](https://github.com/Brettflan/WorldBorder/files/2387299/crash-2018-09-16_23.04.02-server.txt)

Where it crashed:
![image](https://user-images.githubusercontent.com/10309346/45604775-cc4cfb00-ba05-11e8-9c33-621cb5059d9b.png)

Not clear if this is WB, Dynmap or Paper related.
-Steve

**Comment by Brettflan** [comment]
Wouldn't expect it to be anything to do with WorldBorder, and the stack trace contains only NMS code references. Looks to be a problem with Paper/Spigot/Bukkit/Minecraft rather than a plugin, based on that.
