### ISSUE TITLE
Very slow fill on 1.12

### ISSUE THREAD

**Issue by sync667** [Brettflan/WorldBorder#109]
Hello, 

We have to pre-render custom map with OTG and fill command. Problem is that we use last spigot, otg for 1.12 and it's clear install on server with 32 cpu's every to 3,7GhZ, 64gb ddr4, 500GB SSD with very fast access. So hardware and software is i think fine.

After changing server 2 times and trying many combinations with /wb fill 100-10000 0 false we got usually that. 

![shu_djrlbn1](https://user-images.githubusercontent.com/1151335/45845129-86a17280-bd24-11e8-8057-4c8279046b38.png)

As you see it's almost impossible to render map that have only 16k x 16k. We are doing it from 3 days with that result at this moment. I never had that problem with fill by years.

**Comment by Brettflan** [comment]
Yeah, strange. Clearly you have plenty of memory, which would have been one of the two things I'd think most likely to cause the sort of problem. The other thing would be setting too high of a frequency on the Fill command. Since you mention trying 100-10000 for the frequency, you might try the default frequency of 20 to see if that helps. As powerful as your server is, I kind of doubt it in your case, but overly high frequencies can actually un-intuitively cause that sort of slowdown instead of improving the speed.

One other thought, you are using version 1.8.7 of the plugin since you're on 1.12, right?

**Comment by sync667** [comment]
Cpu's can have 3,7 on HT normally from start from 2,5. Yea that's right i'm on 1.8.7 with final build of spigot for last 1.12. I tried to use Paper as well.

**Comment by Brettflan** [comment]
Do you have any other plugins running which make changes to world generation? Those could cause the process to take longer. Or do you have a mapping plugin like DynMap running? If so, you might consider disabling map updates temporarily for it until the process is complete, and do a fullrender after the world is generated.

One other thing I can think of which you might try would be to set a higher value (or possibly 0) for the fillautosave option to see if that helps.

/wb fillautosave [seconds] - set the interval for automatic saving of the world during the Fill process. Default 30 seconds, set to 0 to disable automatic world saving (not recommended).
Permission: worldborder.fillautosave

**Comment by sync667** [comment]
Dynmap was tested to but for now i disabled it at all and tried fillauto. With 0 it's helps a little bit, but still i have to restart server time to time.

**Comment by Brokkonaut** [comment]
Maybe setting the max memory to a lower value might help. If max memory is very high, many chunks can be kept loaded which can slow down the server.

**Comment by DmitryRendov** [comment]
In my experience WB has started eating RAM very aggressively. It dosnt matter how much mem I allocate - always getting 
`Available memory is very low, task is pausing. A cleanup will be attempted now, and the task will automatically continue if/when sufficient memory is freed up. Alternatively, if you restart the server, this task will automatically continue once the server is back up.`

Also, thank you for hint with chunksPerRun value - I reduced it to 1 and the process became faster.

**Comment by jakewtaylor** [comment]
Hi - I'm having this issue on Paper build 167 for Minecraft 1.14.4, using WB 1.9.10 beta. I was getting issues running out of memory, but disabling dynmap while I generate chunks seems to fix that. But it is going _very_ slowly:

![image](https://user-images.githubusercontent.com/8126758/63098466-e6bb8b80-bf6a-11e9-9a61-5e673f0b4acc.png)

@DmitryRendov what is the `chunksPerRun` value you mention?
