### ISSUE TITLE
40 % /fill and server restart !!

### ISSUE THREAD

**Issue by Bobbbe** [Brettflan/WorldBorder#112]
i have a small problem whit WB i do a "/wb (world) 20 208 true" but after 40% the server restart !! no log in console, just server restart ! 
you have suggestion ? or another command for me ?
(server 1.13.1 spigot last version worldborder)

**Comment by Brettflan** [comment]
There should be something in your server log. Otherwise, you probably have something more seriously wrong with your server.

**Comment by Bobbbe** [comment]
ok I found it was the memory blocking.
it is possible to add an option in the plugin that would offer us not to exceed a certain number of memory or to be able to tell him that we have 8, 12, or 32 gig of memory? and if reached the maximum of memory the plugin slow down, I do not know lol it was an idea :)

**Comment by Bobbbe** [comment]
for the moment it's very long, I have maps of 7000 x 7000 and to have a 'Fill' I must restart the server before it reaches the maximum of memoir if the server starts again with errors and the 'Fill' must start at zero again.

**Comment by Brettflan** [comment]
The Fill process by default automatically pauses when the available memory (out of the total memory allocated to the Spigot server process) drops below 200 MB.
When it automatically pauses, it tries to force garbage collection on the server to free up memory, and then waits for enough free memory (500 MB by default) before continuing. This can be configured by editing the value for "fill-memory-tolerance" in the config.yml file.

The Fill process skips over chunks which it sees are guaranteed as fully generated. It still has to process chunks very near the edge of what is currently at least partly generated to make sure they get fully generated, but anything inside of that is very quickly skipped.

**Comment by Bobbbe** [comment]
ok I understand, I'm with 'omgserv', the problem comes from them I imagine because this server says 'unlimited' gives the memory if necessary, the host should not give the memory at the right time and restart the server before that the plugin can stop and restore memory.
