### ISSUE TITLE
Dynmap fullrender doesn't render fully

### ISSUE THREAD

**Issue by Luysita** [Brettflan/WorldBorder#113]
Hello,

Yesterday I re-installed dynmap in my creative server and proceeded to do /wb fill and /dynmap fullrender.
However it doesn't fully render, it stops in the middle somehow, going flat to surface really quickly.
Now sure what's going on, could anyone help me?

**OS:** ubuntu 16.04 LTS
**Dynmap version:** Dynmap version: core=3.0-beta-1-129, plugin=3.0-beta-1-129
**Spigot Version:** This server is running CraftBukkit version git-Spigot-f6a273b-e3d7b2f (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

![2018-10-14-15-10-1123-kmdncjqr4g](https://user-images.githubusercontent.com/4097013/46917883-b100eb80-cfc3-11e8-9933-93efa09134fb.png)
![2018-10-14-15-10-1122-r8u72kvfk2](https://user-images.githubusercontent.com/4097013/46917886-b2caaf00-cfc3-11e8-9e50-871a33cd1573.png)

**Comment by menelmir** [comment]
So, as this is issue is not resolved, I made a very little plugin witch refresh all chunks in all worlds.
And... IT'S WORKS ! Waiting for this issue to be resolved, it's a a temporary solution.
It's provided as is and comes with no warranty, save your server first.
Make sure your read the joigned readme.txt file !!!
Just a command to use, from console.

[ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip](https://github.com/Brettflan/WorldBorder/files/2568502/ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip)

**Comment by menelmir** [comment]
So, as this is issue is not resolved, I made a very little plugin witch refresh all chunks in all worlds.
And... IT'S WORKS ! Waiting for this issue to be resolved, it's a a temporary solution.
It's provided as is and comes with no warranty, save your server first.
Make sure your read the joigned readme.txt file !!!
Just a command to use, from console.

NB : there can exist issues on some case in large worlds... Beware...

[ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip](https://github.com/webbukkit/dynmap/files/2568499/ChunksRefresher_0_0_1-SNAPSHOT-2018-11-02.zip)
