### ISSUE TITLE
Exception Generating new Chunk

### ISSUE THREAD

**Issue by zerafox** [Brettflan/WorldBorder#117]
Attempting to fully generate my Custom Map (via Epic World Generator's Image to Map system) I found my console spitting this error out:
[New Chunk Exception](https://pastebin.com/pEiS017G)

[16:58:25] [Server thread/INFO]: [WorldBorder] Enabling WorldBorder v1.9.0
27.11 22:29:46 [Server] INFO This server is running CraftBukkit version git-Spigot-a1ba5fe-b4230a9 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
WB:

**Comment by Brettflan** [comment]
The problem would be with either the custom world generator process or in Spigot/CraftBukkit itself.
