### ISSUE TITLE
fill command slow

### ISSUE THREAD

**Issue by timr2000** [Brettflan/WorldBorder#119]
Its going OK for a few minuten but after that the tps drops alot "using default settings" and its going verry slow.. loading an large map and this takes ages to load. how to speedup this process? Using paperspigot 1.13.2

**Comment by madtomic** [comment]
How large is the fill and what type of the system computer hardware, you are using?

**Comment by timr2000** [comment]
Default fill.. 20. This is my hardware https://ibb.co/SysLx2K got 5 ram

**Comment by timr2000** [comment]
Server is not crashing but its verry slow with an big map

**Comment by timr2000** [comment]
Shared hosting i a no-go for me, Running an VPS, The problem is.. That the first minutes of rendering the render goes pretty fast and it loads lots of chunks. After a few mins the chunk render is going down and the TPS too.. It keeps the chunks loaded and i think that's an big problem.

**Comment by Brettflan** [comment]
The Fill process keeps just a small number of current chunks loaded to allow full generation, adding them to Bukkit's chunk unload queue as they pass that threshold.

It's possible those chunks are not getting unloaded for some reason, but if so, there's nothing I can do from the plugin side of things beyond that.
