### ISSUE TITLE
loading Chunks error

### ISSUE THREAD

**Issue by timr2000** [Brettflan/WorldBorder#120]
Paperspigot 1.13.2 

https://pastebin.com/TXn6ffda

**Comment by Brettflan** [comment]
The relevant part near the start:
`java.io.IOException: Disk quota exceeded`

Looks like you used more disk space than your host has allotted you.

**Comment by timr2000** [comment]
The host said its using alot of memory.. 30GB total

**Comment by timr2000** [comment]
We are upgrading our server space.. we used alot of space with pre rendering the map+running dynmap on it.. big mistake lol. Thanks for replying this problem is fixed
