### ISSUE TITLE
Maximum border radius from any (X,Y) of 9999

### ISSUE THREAD

**Issue by LukeCS1** [Brettflan/WorldBorder#123]
On 1.13.2,

On large maps, it would seem that from any given (X,Y) coordinate, a radius can exist of any size in memory, but when saving to disc, it seems to limit to 9999 blocks.

Is it possible to fork and change this? Could you send me the specific blob of code required?

**Comment by Brettflan** [comment]
Can't reproduce in Spigot 1.13.2 or Paper 1.13.2, and a problem like that with the plugin shouldn't be possible.

The problem is something else on your server.
