### ISSUE TITLE
/wb fill crashes in 1.14

### ISSUE THREAD

**Issue by roopekoo** [Brettflan/WorldBorder#126]
Server: Spigot 1.14
Plugin: Worldborder 1.9.0
-----------------------------
This plugin works otherwise well in 1.14 but when I try to fill un-generated areas, it fills about 1000-9000 chunks before crashing by a ticking world.
Latest.log: https://pastebin.com/mU8K9xEs
Crash report: https://pastebin.com/XL1syrx9
-------------------------------------------------
How to reproduce:

Run spigot server 1.14
Have Worldborder 1.9.0 installed
set worldborder to eg. 2000 blocks away from spawn
do command /wb world fill
confirm
wait about a minute
Crash

**Comment by mrfloris** [comment]
https://bugs.mojang.com/browse/MC-148830

**Comment by roopekoo** [comment]
Thanks for pointing out that this is a vanilla 1.14 bug. I guess that we have to wait until 1.14.1 or 1.14.2 then...
