### ISSUE TITLE
Crash when confirming fill

### ISSUE THREAD

**Issue by Misio12320** [Brettflan/WorldBorder#128]
[crash-2019-05-05_12.29.12-server.txt](https://github.com/Brettflan/WorldBorder/files/3145451/crash-2019-05-05_12.29.12-server.txt)
Hello again. Server crash when I try "confirm" the fill to 100% again. Minecraft version 1.14.
 This server is running CraftBukkit version git-Spigot-1eece4f-84400e6 (MC: 1.14) (Implementing API version 1.14-R0.1-SNAPSHOT)
> [13:03:05] [Server thread/INFO]: You are running the latest version.
More info?

**Comment by Brettflan** [comment]
No indication of anything in that stacktrace or entire crash report to do with WorldBorder.

The likely culprit is indicated in the stacktrace:
`org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register net.citizensnpcs.trait.Gravity@7c2c3272 while not enabled`

So... it looks like the plugin "citizensnpcs" is disabled but for some reason still trying to register stuff. Whatever the case, again, nothing to do with this plugin.

**Comment by Misio12320** [comment]
just for confirm to let don't remove chunks which are important. I have to remove the plugin right?
