### ISSUE TITLE
Crashing in 1.14.1 using /wb fill (Worldborder 1.9.0)

### ISSUE THREAD

**Issue by northerncarrots** [Brettflan/WorldBorder#130]
After generating for around 20 hours, my server crashed.
The server will now crash upon trying to resume the filling process.

1. Run Spigot-8043ebc-dd99c5b (MC: 1.14.1) (Implementing API version 1.14.1-R0.1-SNAPSHOT) or Paper-21 (1.14.1)
2. Use Worldborder 1.9.0
3. `wb world set 25000 25000 0 0`
4. `wb shape square`
5. `wb fill` + `wb fill confirm`
6. wait for **x** amount of hours
7. crash

**Logs**
[Spigot-8043ebc-dd99c5b](https://hastebin.com/resiqiviqa.md)
[Paper-21](https://hastebin.com/usuceqadux.md)

_The server crashes at around the 270,000s_.

**Comment by Brettflan** [comment]
The stack traces indicate the problem being in Spigot/Bukkit/NMS, no code from any plugins at fault. There is at least one known NMS bug along these lines which may or may not be fixed yet. Whatever the case, look to Spigot/Paper for a fix.

**Comment by northerncarrots** [comment]
Thank you.

Please excuse my ignorance but would you happen to know how to narrow it down to the coordinates that reproducibly cause this? I submitted issues to both Spigot and Paper and was told

> You need to narrow this down to the seed and coordinates that reproducibly cause an issue.

from the former and had my issue closed.

**Comment by Brettflan** [comment]
> Please excuse my ignorance but would you happen to know how to narrow it down to the coordinates that reproducibly cause this?

No idea offhand, sorry. You could maybe guess the region based on which region file was modified last, but not the specific chunk. Maybe the region coordinates would be sufficient for them, though.
