### ISSUE TITLE
How many thread can WorldBorder use?

### ISSUE THREAD

**Issue by gundami** [Brettflan/WorldBorder#132]
Hi,
My server' cpu has 40 threads and worldborder only use 2 threads. How can i use all the threads to fill the world?

**Comment by olodar** [comment]
Didn't found solution?

**Comment by Brettflan** [comment]
Filling the world relies on the vanilla chunk loading/generating methods, Those methods were (and probably still are?) run through a single thread in a queue. There's nothing this plugin can do about that.

I'm no longer actively developing this plugin, so I haven't kept up with developments. It's remotely possible those methods were made thread-safe and able to be run multi-threaded, but I doubt it.
