### ISSUE TITLE
event is Deprecated

### ISSUE THREAD

**Issue by NTDLX** [Brettflan/WorldBorder#136]
[WorldGuard] "WorldGuard v7.0.0-SNAPSHOT;1887-36d25c0" has registered a listener for org.bukkit.event.entity.EntityCreatePortalEvent on method "public void com.sk89q.worldguard.bukkit.listener.WorldGuardEntityListener.onCreatePortal(org.bukkit.event.entity.EntityCreatePortalEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [].

**Comment by NTDLX** [comment]
paper-44 （1.14.1）

**Comment by Brettflan** [comment]
WorldGuard is a different plugin.
