### ISSUE TITLE
Border size resetting to 9999 on server restart

### ISSUE THREAD

**Issue by BlackBeltPanda** [Brettflan/WorldBorder#150]
Running WorldBorder 1.9.10 on Paper 1.14.4 Build 152.

I set a world border radius at 50k. Every time the server restarts, the border radius changes to 9999. It's the only thing in the config that resets as far as I can tell; my other settings remain unchanged. No errors at startup.

This is my config (when it's not reset to 9999): https://pastebin.com/raw/nSpXmmqP

**Comment by Brettflan** [comment]
One other person posted with that problem:
https://github.com/Brettflan/WorldBorder/issues/123

I still have no idea what oddity might cause that, as there is no limit of that sort in WorldBorder's code, and only that one other person has reported this problem. I can't reproduce it, and it seems almost nobody else has that problem either. There's presumably something strange going on related to your particular server setup.

Whenever a border is set or resized or deleted, or anything other configuration changes, the config file is immediately updated.
Can you change the border size and then check the config.yml file for WorldBorder to see if the radiusX and radiusZ values for that world are updated or not, and report back?

**Comment by BlackBeltPanda** [comment]
As you've said, it does update properly in the config when I use the command to change the radius.

The server host being used is AnvilNode with MultiCraft as the control panel. No other configs are reset in any way so I don't think anything with the host would be causing it.

The plugins installed at the moment are:
`AdvancedPortals, AsyncWorldEdit, BlockLocker, ChatControl, ChestSort, CoreProtect, Essentials, EssentialsSpawn, Images*, JupiterCore, LaggRemover, LuckPerms, MoneyHunters, NPCAuctions, PandaRandomEnchant, PlaceholderAPI*, PluginConstructorAPI, ProtocolLib*, QuickShop, RandomTeleport, SAML, ServerListPlus*, SlotMachine, TimeIsMoney*, TitleManager*, Vault, WorldBorder, WorldEdit, WorldGuard`

I'm going to play around with it a bit and see if I can replicate it on another machine.

**Comment by BlackBeltPanda** [comment]
Update:
I contacted my server host to ask if it's on their end. Their response was it is on their end but the staff member wasn't sure why. I'll just set something up to reset the border to the value I want when the server starts up. Closing this since it's not on WB's end. =)

**Comment by Brettflan** [comment]
Thanks for the update that it is indeed a host problem, that's useful to know.
