### ISSUE TITLE
WB Reset to 99999

### ISSUE THREAD

**Issue by Zeprize** [Brettflan/WorldBorder#166]
When ever I restart the server the WB resets to 99999 even if I change it in the config
Here are my plugins

` AdvancedBan*, Banknotes*, DiscordSRV, dynmap*, Essentials, GUIShop, IllegalStack, LuckPerms, MassiveCore, NametagEdit*, OldCombatMechanics, PlaceholderAPI, PluginConstructorAPI, ProtocolLib*, RankGrantPlus, Spartan, TabList, TimeIsMoney*, Vault, ViaVersion*, WorldBorder, WorldEdit`
Server Host: `Shockbyte`
'PaperMC 1.13'
Map: `1:2000 Earth Map (so kinda needed to fix this)`

**Comment by Brettflan** [comment]
It's your host Shockbyte sneakily modifying your configuration to limit your border size.

https://github.com/Brettflan/WorldBorder/issues/159
