### ISSUE TITLE
/wb fill does not work correctly

### ISSUE THREAD

**Issue by luckybl0ck** [Brettflan/WorldBorder#171]
When you start loading the world in the console, messages about chunk loading are displayed, but the map is not loaded on DynMap. If players load the world manually, DynMap works perfectly.

**Comment by Brettflan** [comment]
The problem is with DynMap not keeping up. If there are no errors in the log from the Fill process and it indicates it completed, then the target chunks were loaded/generated, whether or not DynMap is showing them yet.
