### ISSUE TITLE
[Feature request] fill and trim command resuming after server restart

### ISSUE THREAD

**Issue by johncsuti** [Brettflan/WorldBorder#175]
The plugin should have a way to resume its operation after a server restart.

**Comment by Brettflan** [comment]
The Trim task finishes quickly enough that there's no purpose in saving and resuming it. The Fill task has featured saving and resuming itself on server restart since it was implemented years ago, barring the server completely crashing and not exiting properly.

So.... what are you talking about?

**Comment by johncsuti** [comment]
The server fill command never resumes after a restart in any of the three servers I have this on. Could be something with the server but considering there isn’t really a config I don’t think so.

**Comment by Brettflan** [comment]
It sounds like maybe you aren't properly shutting down your servers using the stop command and are instead just killing their process or something similar.

**Comment by johncsuti** [comment]
the process I use is the restart command in paper it shuts down the server and runs a script I programmed to launch the server

**Comment by Brettflan** [comment]
Well, no idea what's going wrong on your end.
