### ISSUE TITLE
Fall damage due to worldborder

### ISSUE THREAD

**Issue by Blueeyestar** [Brettflan/WorldBorder#176]
if you get to the wordlborder too often, you will be teleported to the middle of the map where you fall into the dead from above. This problem is brand new. Then you die of falling damage.

paperversion: Paper version git-Paper-93 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

worldborder : WorldBorder 1.9.10 (beta)

**Comment by Brettflan** [comment]
Does that world have a safe spawn point set in it? If not you might want to set it, as that's where people will be teleported if no safe Y location can be found at the X/Z coordinates it tries to move them to back inside the border.

**Comment by Blueeyestar** [comment]
I did that. It works. but why are they teleported to the spawn? can you turn that off?

**Comment by Brettflan** [comment]
I mentioned why it's necessary above, so: no.
