### ISSUE TITLE
Worldborder 1.9.10 Beta 1.15.2 Paper[Issue]

### ISSUE THREAD

**Issue by TimRambo** [Brettflan/WorldBorder#179]
I don`t know why i got this.
Everything has worked fine suddenly this pops ups [See Pastebin]
https://pastebin.com/W9D9gjYd

idk if this is WB but it happen in WB fill like when it says blablabal loaded etc 
[02:30:06 WARN]: Skipping Entity with id

**Comment by Brettflan** [comment]
Doesn't look like anything WorldBorder could do about the error in that stack trace. Check for Paper/Spigot updates and maybe try it again.

**Comment by TimRambo** [comment]
ok thx 👍
