### ISSUE TITLE
Add LICENSE information

### ISSUE THREAD

**Issue by Prof-Bloodstone** [Brettflan/WorldBorder#187]
@Brettflan I know that this plugin is no longer supported. That's why I want to ask you to add LICENSE information, so that the community can fork and develop it further without any potential legal issues.
Currently, the only mention is that:
> The source is under the extremely permissive BSD license and as long as you maintain a link back to the original project somewhere (even in a text file somewhere in the project), you're welcome to do what you like with it.

Thank you for your amazing work over the years.

**Comment by Brettflan** [comment]
Huh, I could have sworn I had the license in place long long ago. Apparently not.

Added:
https://github.com/Brettflan/WorldBorder/commit/44f388f3ba8d5d84d6e4cf223beedf8bc35c7191
