### ISSUE TITLE
1.16 support?

### ISSUE THREAD

**Issue by srnyx** [Brettflan/WorldBorder#188]
Does this plugin work on 1.16.x?

**Comment by docwhomc** [comment]
It should.  I'm working on a major overhaul to add support for additional border shapes and integration with other plugins on [my fork](https://github.com/docwhomc/WorldBorder).  I also set up a discord server for it: https://discord.gg/ePNBgMG

**Comment by Tsoccerguy3** [comment]
You should be aware that on many of the 1.16.1 ports i have test , trim does not work on spigot or paper .

https://github.com/PryPurity/WorldBorder/issues/8

**Comment by srnyx** [comment]
> You should be aware that on many of the 1.16.1 ports i have test , trim does not work on spigot or paper .
> 
> [PryPurity#8](https://github.com/PryPurity/WorldBorder/issues/8)

How about 1.15?

**Comment by Tsoccerguy3** [comment]
Yes , 1.15.2 is fully functional , you just need to know that if you are doing a fill or a trim some plugins can open chunks and stop a trim from completing . I use it for maintenance , to set borders ,  generate the map and trim . You may need to disable dymap to get a well groomed world and then enable dynmap to render your worlds

**Comment by Tsoccerguy3** [comment]
Brett , I checked the flyout areas after a trim with the standalone editor Amulet https://github.com/Amulet-Team/Amulet-Map-Editor/releases . Trim does not work on 1.16.1

**Comment by Brettflan** [comment]
I explained over there how it works at least in my code. There's a small possibility something has changed with his fork that broke it, or it could be something changed in MC 1.16; whatever the case, I no longer support the plugin, I just wanted to step in and explain how it (hopefully still) works.

**Comment by Tsoccerguy3** [comment]
Pry misunderstood he closed the issue .

**Comment by Tsoccerguy3** [comment]
Brett , Maybe you can update your readme and main page , to send people to Docwhomc's Discord to get those people working together for updates

**Comment by Brettflan** [comment]
It's my understanding there are 2-3 forks different people are working on. I don't want to show favoritism for any one in particular, nor do I want to have to keep track of an ongoing list of forks people are working on. After a while, if maybe one fork has shown itself to have more activity and stayed active, I might update the readme to point to it.
