### ISSUE TITLE
Error with last version of WorldBorder

### ISSUE THREAD

**Issue by fabien91** [Brettflan/WorldBorder#49]
http://pastebin.com/mzVVSvWD

**Comment by Brettflan** [comment]
When running WorldBorder's Fill, an error like this is basically guaranteed to either be in Spigot/Bukkit/NMS or in a plugin or mod which does something related to world generation code. In your case based on the stacktrace, it is occurring in Spigot/Bukkit/NMS code, no sign of a plugin or mod interfering.
