### ISSUE TITLE
Odd teleport in world_nether at 1.9

### ISSUE THREAD

**Issue by dfdgsdfg** [Brettflan/WorldBorder#59]
If I try to teleport form world to world_nether through a vanilla portal, it teleport me to somewhere else not in front of the nether portal with WorldBorder's message which is configured.

Here is my plugin list and WorldBorder's config file.

https://github.com/semaulhq/plugins.

It appear every spigot build after 1.9.

**Comment by Brettflan** [comment]
It's a bug in Spigot to do with the PlayerTeleportEvent not always reporting the correct getTo() location in relation to nether portal teleportation. Take it up with them.

**Comment by dfdgsdfg** [comment]
Report this to spigot issue tracker.

https://hub.spigotmc.org/jira/browse/SPIGOT-1906

**Comment by mibby** [comment]
Also occurs with end portal. Players being tped to the spawn location randomly when entering the end portal instead of the default end spawn location.
