### ISSUE TITLE
Worldborder not showing up on dynmap 2.3

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#64]
The worldborder is no longer showing up after updating dynmap from 2.3 alpha 3 to stable 2.3

**Comment by Brettflan** [comment]
Can anyone else confirm the border not showing up on Dynmap 2.3, rather than this just being the occasional Dynmap screwiness?

**Comment by Sikatsu** [comment]
I guess it's the rare dynmap screwiness then, it works now. I'm not that familiar with Worldborder. Can be closed lol :)
