### ISSUE TITLE
[Feature Request] Worldborder middle point teleport

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#68]
Hello,

I have set my worldborder earlier, but I'd like to make my worldborder bigger soon.

Is there anyway for me to check where the middle of the worldborder is and where my worldborder radius is set too?

It would be nice to see what radius I have set it to and to teleport to the middlepoint so I can easily make it bigger.

Currently, I have no idea how I could safely extend the worldborder.

Thanks in advance,

Sikatsu

**Comment by Brettflan** [comment]
http://dev.bukkit.org/bukkit-plugins/worldborder/pages/commands-and-permissions/

/wb list - shows list of all borders, center position and radius
/wb world_nether radius +100 - increase border radius for world "world_nether" by +100

**Comment by Sikatsu** [comment]
Oh, lol. Nice. Stupid me, thanks!
