### ISSUE TITLE
Worldborder extended, but dynmap can't render the new parts?

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#69]
I just extended my worldborder (http://mc.villagercraft.eu:8050/) but can't seem to render the new parts.

When I use /dynmap radiusrender or /dynmap updaterender, it immediatly says completed and won't render the new parts.

**Comment by Brettflan** [comment]
Have you run the Fill command to actually force generation of all chunks inside the border?

**Comment by Sikatsu** [comment]
@Brettflan 

I used /wb world2 fill and /wb fill confirm. The progress took quite long and finished last night on 100%.

But when I opened dynmap, I still saw black places, so I used /wb world2 fill again, which went from 77.7% to 100% in less then 10 minutes, with nothing changed on dynmap.

I'm still unsure how I can get rid of those small black squares and big black line above.

**Comment by Brettflan** [comment]
If the Fill process completed successfully, then those parts of the world are generated and exist. It's down to Dynmap to finish rendering them. Dynmap might eventually get those rendered, or you may need to do a full render. Either way, your problem should be with Dynmap.

**Comment by Sikatsu** [comment]
Alright, currently doing an updaterender and it seems to do something. Thanks!
