### ISSUE TITLE
Server Crash When attempting to fill world.

### ISSUE THREAD

**Issue by JamieSinn** [Brettflan/WorldBorder#70]
https://gist.github.com/JamieSinn/859882ef8932c0ee1cbbc52a530fe681

**Comment by Brettflan** [comment]
Based on the error it's running into a problem within CraftBukkit code while trying to save the world to disk.

Do you have enough free space? Is something else besides the Spigot server itself possibly locking one of the world data files? If neither of those seems to be a problem, perhaps another plugin or mod might be accessing the world files directly (for example a mapping plugin).

Please do post back again if you get it figured out, I'm curious as to the cause myself.

**Comment by JamieSinn** [comment]
I'll look into that. I was tracing the stack back through spigot, but it seems like you're on the right path.
I've also submitted this to spigot for review.
https://hub.spigotmc.org/jira/browse/SPIGOT-2712

**Comment by JamieSinn** [comment]
```The world saving took longer than the default timeout value of 30 seconds because the number of chunks to save exceeds your servers performance.
Would you could do:
Fill the world slower (less chunks per tick)
Let the world save more often
Increase the timeout value of your Spigot server
Get a better server```

I'm entertained at the last point, (from the spigot thread).

Turns out timeout needs to be increased quite a bit, maybe mention with a large world radius fill that this needs to be done?

**Comment by Brettflan** [comment]
By timeout, I assume he's referring to the "timeout-time" Spigot setting?

One other question, were you running at the default Fill frequency, or did you specify a higher frequency? Overly high frequencies can actually cause the process to go slower (which is unintuitive) or cause various other problems.

**Comment by JamieSinn** [comment]
Not sure, I assume it's the default fill frequency.

**Comment by JamieSinn** [comment]
Turned out to be the timeout that just had to be increased.
