### ISSUE TITLE
Bug with Spigot

### ISSUE THREAD

**Issue by MrsMeowys** [Brettflan/WorldBorder#71]
There is a bedrock glitch, which is happening with portals that are too far from spawn (I don't have the exact distance) where once you go back in the Nether it'll teleport you to the edge of the world with an error message, and players will die in the bedrock/void.

WorldBorder Version: 1.8.6

Spigot Version: This server is running CraftBukkit version git-Spigot-047f737-744e1a1 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

Video: https://www.youtube.com/watch?v=4F6WDjT5CyY

**Comment by Brettflan** [comment]
Sounds like this issue, which is indeed a problem in Spigot.
https://github.com/Brettflan/WorldBorder/issues/59

**Comment by Brettflan** [comment]
Apparently it is indeed fixed as of yesterday, according to one of the main Spigot devs:
https://hub.spigotmc.org/jira/browse/SPIGOT-2733?focusedCommentId=22049#comment-22049
