### ISSUE TITLE
Question about worldborder extention

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#73]
Hey,

Would the new mansions from 1.11 show up if I'd extend the worldborder? Or is a world reset required?

Thanks in advance.

**Comment by Brettflan** [comment]
Offhand, I don't know. This is the first I've actually heard of mansions being added. If the mansion can in fact show up in newly generated chunks in an old world, then the answer is yes. But it may instead require a new world for the new world features.

Whatever the case, it's not really anything to do with WorldBorder.

**Comment by Sikatsu** [comment]
Well, the reason I link this to worldborder, is because as far as I know due to the worldborder, chunks outside of it won't be generated.

So, if I'd extend the worldborder and new chunks are being generated, I wonder if new structes from minecraft versions would show up, or that it still needs a world reset.

Thanks for your reply btw :)

**Comment by Brettflan** [comment]
Well yes, those chunks are of course not generated until somebody moves out close enough for them to generate, or until you run a Fill or similar routine that generates chunks.

Whether the mansions will even generate in an older world is the question, and I don't have that answer.
