### ISSUE TITLE
1.9+: All boats are changed to oak boats

### ISSUE THREAD

**Issue by Black-Hole** [Brettflan/WorldBorder#74]
1.9 introduced 6 boat types. If you ride a boat into the world border, the boat type is reset to oak boat.

It's caused by:
https://github.com/Brettflan/WorldBorder/blob/master/src/main/java/com/wimbli/WorldBorder/BorderCheckTask.java#L86

Since 1.9 boats does not visually glitch like before. So it would be possible to teleport the boat, too. (Then you'll have to call eject() a seconds time because the boat might have a second passenger.)

Or you could spawn a new boat and set the type of the old boat.

**Comment by Brettflan** [comment]
Confirmed in MC 1.9. Removing the special handling for boats so that they're handled like other rideable entities does indeed seem to work now, so I've done that.

https://github.com/Brettflan/WorldBorder/commit/ed0c46a55781af4b9c3178e94b40c7cb8c8b080d
