### ISSUE TITLE
Insane lag/crashing/issues while filling in 1.11

### ISSUE THREAD

**Issue by andrewkm** [Brettflan/WorldBorder#75]
WorldBorder crashing players online while filling in 1.11
Happens after a while online, client error is simply "null" ... server console showing no errors.

Happens if you're in the world you are filling or if you're not. Same thing.

Update:
Yup fill task is causing some insane lag.
This is with Nobody online what so ever, generating a normal world (not nether or end) http://i.imgur.com/S6wTWnd.png

**Comment by Brettflan** [comment]
Are you using default Fill settings, particularly frequency? Do you have any other plugins which modify world generation?

**Comment by andrewkm** [comment]
I got the issue down with one of my devs. Another plugin running a save-all during your WorldBorder is what's causing the massive insanity / lag / crashing.

Simply disabling bukkit's autosave fixes it. The fact you are running a world save during bukkit's autosave is for some reason causing serious issues in 1.11

I have ran at least 10-20 fill tests (not exaggerating) and of course absolutely all default settings (been doing this for six years and using your plugin since the very first release. The bukkit ticks per autosave (in bukkit.yml) is the issue. If it's at anything but 0 it'll eventually rape WorldBorder. Can't reproduce on 1.10.2 - completely can with 1.11

Pretty sure if other plugins ran some sort of save-all command during your saves it would case an issue as well.

My advice would be to set some sort of config setting in your plugin as to whether to use your saving method in between the filling or not. Or perhaps a command argument that decides whether or not to use it.

**Comment by andrewkm** [comment]
Here's a crash log btw during the filling process... this is from 1.10.2 as well actually, happens at rare occasions but never bothered reporting it. Might as well show you:

http://pastebin.com/raw/JrfA16Tk

**Comment by Brettflan** [comment]
There is in fact a command and config setting to determine how often the Fill process autosaves the world.

/wb fillautosave <seconds> - set the interval for automatic saving of the world during the Fill process. Default 30 seconds, set to 0 to disable automatic world saving (not recommended).

Permission: worldborder.fillautosave

**Comment by andrewkm** [comment]
I dunno man, although I worked my way around this, I seriously think you need to look into this with all the server crashing/etc.

I do appreciate the quick replies though, thanks :)

**Comment by andrewkm** [comment]
Setting the setting you mentioned to 0 does work while keeping bukkits setting the same, however this crash still happens occasionally usually, main part of that dump above:

http://pastebin.com/raw/EVWNLByj

**Comment by Brettflan** [comment]
That specific stacktrace you just posted isn't possible if you have the fillautosave option set to 0, as the indicated source code line would then be unreachable.

Specifically this in the stacktrace:
com.wimbli.WorldBorder.WorldFillTask.reportProgress(WorldFillTask.java:399)

**Comment by andrewkm** [comment]
That stacktrace was with default fillautosave option.
As well was with no other plugins running an auto save including bukkit.yml

**Comment by andrewkm** [comment]
All good seems to work now.
