### ISSUE TITLE
Worldborder fill not working correctly (I think?)

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#77]
So I used /wb fill over the night. As seen in the logs it said ''task completed''. However when I run /wb fill again, it starts from 75%. So it's not completed then? I'm confused.

[WorldBorder] [Fill] 7791 more chunks processed (3621127 total, ~99.9%) (free mem: 3799 MB)
[WorldBorder] [Fill] task successfully completed for world "world2"! (free mem: 3717 MB)

**Comment by Brettflan** [comment]
The Fill process will run through all chunks to make sure they're generated every time. The process should go through very quickly if everything has already been generated though.

**Comment by Sikatsu** [comment]
Not really. It's going just as slow as it went over the night. I'm at 82% now. 

Isn't it suppose to skip already generated chunks? And if so, why does it just restart from 75%? When I started yesterday, it started at 69%.

**Comment by Sikatsu** [comment]
What should I do once this one is completed, run /wb fill again to check if it's actually completed? O.o confused on this one.

**Comment by Brettflan** [comment]
It does indeed skip already generated chunks, after checking to make sure they are fully generated, which takes almost no time. Those chunks are still counted in the total even if they didn't need to be loaded/generated.

The percentage is based on how many chunks have been checked. So if it is able to check through 75% of the total chunks in the first 5 seconds (which is sensible if they're already full generated) before giving the first report, it will report 75% progress, as you would expect.

Once it is finished, it is finished. No need to run it again unless you've got something else going on with your server, like the world not being properly saved to disk as the process goes through and after it completes.

**Comment by Sikatsu** [comment]
I see. Yes it indeed skipped chunks, thats why it went to 69% and started from there to 100% over the night. However once I woke up I used /wb fill again, then it skipped to 75% and started from there to 100% (still in progress)

And that's what I don't get, because over the night it already was 100%, shouldn't it skip completely then because everything is generated? That's the thing i'm confused about. Using frequency 1000 (0 players)

**Comment by Sikatsu** [comment]
@Brettflan When that was finished, I did /wb fill again and it started from 73%. I cancelled it though, as this would be an infinite process. But is this correct? (and does it matter that I cancelled it?)
