### ISSUE TITLE
[Request] Forge port

### ISSUE THREAD

**Issue by LiskoSlayer63** [Brettflan/WorldBorder#79]
There's apparently zero mods at the moment which offer as much features as your plugin. It would be great to see nice round worlds on modded servers too so is there any chances for Forge port of this plugin?

**Comment by Brettflan** [comment]
Someone did a Forge port of WorldBorder which they released quite some time ago, though I'm not sure what the current state of it is.

Anyway, doesn't Spigot generally work with other mods?

**Comment by LiskoSlayer63** [comment]
@Brettflan I noticed that you mentioned the Forge port on your [BukkitDev page](https://dev.bukkit.org/projects/worldborder) but unfortunately the link redirected to `404 Not Found`, so I assume that there's none at the moment.

> Anyway, doesn't Spigot generally work with other mods?

I was hoping this when I started to exchange my server from Bukkit/Spigot to Forge, but as far as I know it's impossible to run mods and plugins at the same time. If you got more information about this I'll be grateful.

**Comment by LiskoSlayer63** [comment]
@Brettflan Can you consider making a Sponge port? I tried it but I've never modded Minecraft before so it's hard but it looks a lot like a Bukkit.

**Comment by Brettflan** [comment]
I don't have the time or desire to do so, sorry.

**Comment by LiskoSlayer63** [comment]
@Brettflan I have but I have none of experience about programming Minecraft so I can't do it alone. Certainly I have common experience at programming just to make you know.

**Comment by Brettflan** [comment]
If you want to try making a port of it for Sponge, you're welcome to do so. I've never used Sponge, so I can't really help with that end of things, but I don't mind answering questions about my code here or how it works through Bukkit.
