### ISSUE TITLE
trim dont work

### ISSUE THREAD

**Issue by seema84** [Brettflan/WorldBorder#80]
Bukkit/Spigot 1.11.2

the trim command don't work correctly .. not all chunks will remove after the default 208 blocks beyond the border

**Comment by Brettflan** [comment]
You'll need to provide more information. How are you determining that the chunks aren't removed? Does the Trim command return an error, or indicate success? If it indicates success, then it should indeed have been successful.

If you are using a mapping utility like DynMap, IIRC you will need to restart your server and then refresh the map in DynMap for both of them to pick up on the fact that those chunks no longer exist, since normally (without a special utility like WorldBorder's Trim) world chunks are never removed, only added.

**Comment by seema84** [comment]
"How are you determining that the chunks aren't removed?" When i use a dynmap render after the trim command the chunks beyond will not remove. I get no error. Worldborder find no more chunks to remove (on the first trim they found some chunks but not many).
example -> https://picload.org/image/rllgwcpw/trim.png and https://picload.org/image/rllrgggr/trim2.png Only 1-2 chunks after  the 208 blocks will "sometime" remove, beyond will stay. I think dynmap can chunks remove or rerender if they are not exist.

For me the fill command dont work correctly too. https://picload.org/image/rllgwidr/fill.png Many chunks will no fill.

**Comment by Brettflan** [comment]
If no problems were reported by WorldBorder during the Trim, then it was successful.

Based on those first 2 examples, clearly DynMap needs to re-render. As per above, restart your server and then run a fullrender in DynMap to properly refresh its map.


Did you have any problems during the Fill? Did you run the Fill at a higher frequency than default? Did it run low on memory and have to pause at any point?

**Comment by seema84** [comment]
"DynMap needs to re-render." I need to remove all render data befor? I re-render after the trim many times. The result you can see on the pics.

"Did you have any problems during the Fill?" No
"Did you run the Fill at a higher frequency than default?" No
Did it run low on memory and have to pause at any point? I don't know but this server have not many memory. I can try it again and watch the used memory. There was no break.

**Comment by seema84** [comment]
show the difference after re-render ->
https://picload.org/image/rllgwcpw/trim.png 
and
https://picload.org/image/rllrdiri/trim3.png
only 2-3 chunks beyond the default 208 blocks will remove

**Comment by Brettflan** [comment]
Looking at trim3.png, I can clearly see the edge of the actual real existing chunks having that nice black jaggy edge at the bottom between them and the chunks which you trimmed, which no longer actually exist. Those parts of the map in Dynmap haven't been properly wiped/refreshed.

**Comment by seema84** [comment]
So its a dynmap bug?

**Comment by Brettflan** [comment]
That, or more likely you haven't properly wiped/refreshed the map.

Whichever the case, it's not a problem with WorldBorder.

**Comment by seema84** [comment]
Now i have a second time use the fill command (50% memory use) and all holes are created. I don't know why its don't work at the first time.

**Comment by seema84** [comment]
i think you can close this issue. thanks for your help
