### ISSUE TITLE
Non-oak boats are replaced with oak boats when players cross the border

### ISSUE THREAD

**Issue by c0wg0d** [Brettflan/WorldBorder#82]
If a player is in a non-oak boat (spruce, birch, etc.) and they cross the border, when they are teleported back behind the border their boat is changed to an oak boat.

**Comment by Brettflan** [comment]
That was fixed in the last commit several months ago, but it wasn't yet in a release. Since no other fixable problems have come up since then, I suppose I might as well make a release for it.
