### ISSUE TITLE
Server restart, looks like it's crashing, rollback

### ISSUE THREAD

**Issue by Sikatsu** [Brettflan/WorldBorder#87]
Hello,

Everytime when I restart my server thru console it says:

13.07 19:33:14 [Server] INFO Saving worlds
13.07 19:33:14 [Server] INFO Saving chunks for level 'world'/overworld
13.07 19:33:59 [Multicraft] Terminating server via signal
13.07 19:34:00 [Multicraft] Server shut down (terminating)
13.07 19:34:00 [Multicraft] Looks like a crash, check the server console. Return value: 143
13.07 19:34:00 [Multicraft] Server stopped

However as soon as the server started again, the world is rollbacked. Is my world corrupted by running worldborder fill? Is there anyway to fix this?

**Comment by Brettflan** [comment]
Running Fill specifically won't have corrupted your world, no. When it comes down to it, it simply has Bukkit load (and therefore generate) world chunks in a specific order, and then queue them for being unloaded once enough nearby chunks were loaded for full generation.

It would generally come down to what all you are running on your server. For example, mods/plugins which modify world generation, version of Spigot / Minecraft / etc.

With all of the problems you specifically are running into where others generally are not, I'm beginning to doubt there's much I can do to help you.
