### ISSUE TITLE
(1.8.7) Y coords not being kept when pushed back

### ISSUE THREAD

**Issue by LucKYsHoTSzZz** [Brettflan/WorldBorder#94]
This vid will explain it all. https://youtu.be/r2KYTH0rnfo?t=54

**Comment by Brettflan** [comment]
What world/dimension is that in? What are the Y coordinates that the player was at (I see they're not displayed in the video)? Do you know for sure whether the player was pushed back (nearly same X and Z coordinates), or were they instead possibly sent to the default spawn location for that world instead? Is the border set to wrap? Is the border round, or square?
