### ISSUE TITLE
1.13 support?

### ISSUE THREAD

**Issue by TheCompieter** [Brettflan/WorldBorder#96]
Caused by: java.util.zip.ZipException: invalid distance too far back
10:12:24 [INFO] Survival >     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at java.io.DataInputStream.readFully(DataInputStream.java:195) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at java.io.DataInputStream.readLong(DataInputStream.java:416) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagLongArray.load(SourceFile:66) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagCompound.a(SourceFile:437) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagCompound.load(SourceFile:81) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagList.load(SourceFile:69) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagCompound.a(SourceFile:437) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagCompound.load(SourceFile:81) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagCompound.a(SourceFile:437) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTTagCompound.load(SourceFile:81) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.RegionFileCache.read(RegionFileCache.java:89) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:85) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:53) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkRegionLoader.b(ChunkRegionLoader.java:166) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:68) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.lambda$2(ChunkTaskScheduler.java:50) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:49) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:1) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus$1.a(SourceFile:46) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus$1.a(SourceFile:27) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:98) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler.a(SourceFile:60) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_171]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.Scheduler.b(SourceFile:61) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.SchedulerBatch.a(SourceFile:39) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:176) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:166) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:127) ~[Spigot.jar:git-Spigot-69774b3-671581e]
10:12:24 [INFO] Survival >     ... 9 more

**Comment by Brettflan** [comment]
What were you doing when you received that error? I don't see any code from WorldBorder indicated in that stack trace.

**Comment by TheCompieter** [comment]
trying to fill my world border it was always slow almoste crashing my 1.13 server/world lower than 10 tps
cloud it be corruption? 

i had some techinical problem with my server regarding bad sata cable and ram almost lost everything



specs:
core2 quad Q6600
8GB ddr2
ubuntu 16.04.5
java 8 jdk
