### ISSUE TITLE
low tps while filling world border

### ISSUE THREAD

**Issue by TheCompieter** [Brettflan/WorldBorder#97]
i have very low tps in my survival server while filling the world border
i have around 8 to 10 tps and i have 2 gb ram assinged to the survival server
do you have any solution to this or do i just have to wait for it to finnish.

Specs: 
Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz, 4 cores
8 GB Ram 
ubuntu server 18.04.5
java 8 jdk

**Comment by TheCompieter** [comment]
first i did it at default but later i tried higher (100) and it did not change much to my feeling
i think it is the core 2 quad that's holding me back with its single core performance
that one core from my survival is at 100% 

20:53:07 [INFO] Survival > [WorldBorder] [Fill] 42 more chunks processed (364747 total, ~85.4%) (free mem: 879 MB)
20:53:07 [INFO] Survival > [WorldBorder] [Fill] Saving the world to disk, just to be on the safe side. (free mem: 879 MB)
20:53:12 [INFO] Survival > [WorldBorder] [Fill] 56 more chunks processed (364803 total, ~85.4%) (free mem: 814 MB)
20:53:17 [INFO] Survival > [WorldBorder] [Fill] 40 more chunks processed (364843 total, ~85.4%) (free mem: 689 MB)
20:53:22 [INFO] Survival > [WorldBorder] [Fill] 38 more chunks processed (364881 total, ~85.4%) (free mem: 867 MB)
20:53:27 [INFO] Survival > [WorldBorder] [Fill] 41 more chunks processed (364922 total, ~85.4%) (free mem: 527 MB)
20:53:33 [INFO] Survival > [WorldBorder] [Fill] 39 more chunks processed (364961 total, ~85.5%) (free mem: 669 MB)
20:53:38 [INFO] Survival > [WorldBorder] [Fill] 295 more chunks processed (365256 total, ~85.5%) (free mem: 538 MB)

**Comment by Brettflan** [comment]
Well, higher than default Fill frequency will of course definitely cause more and more of a hit to server performance, and can even potentially make world generation slower rather than faster or cause other problems.

**Comment by TheCompieter** [comment]
thanks it's finally done with generating it took a few hours
